version: "3.9"

services:
  node:
    image: node:17-alpine
    container_name: "remote_for_slides"
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: >
      sh -c "
        npm install -g nodemon
        npm install &&
        npm run start
      "
